baseURL = 'https://nothence.com'
languageCode = 'en-us'
theme = 'nothence'
title = 'Nothence'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Releases'
pageRef = '/releases'
weight = 20

[[menus.main]]
name = 'Videos'
pageRef = '/videos'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

